FROM stackbrew/ubuntu:13.10
MAINTAINER greg.lonnon@gmail.com

ENV DEBIAN_FRONTEND noninteractive
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apt-get update
RUN apt-get -y upgrade 
